config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  resources :bills

  resources :payments

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :payment_group
  belongs_to :user
  belongs_to :group
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user
  belongs_to :bill
end

app/models/payment_group.rb
class PaymentGroup < ActiveRecord::Base
  belongs_to :group
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :login
  
  #->Prelang (user_login:devise/username_login_support)
  belongs_to :group
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {value: login.downcase}]).first
    else
      where(conditions).first
    end
  end


  devise authentication_keys: [:login]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  #->Prelang (user_login:devise)
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up)        { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in)        { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end


  private
  
  #-> Prelang (user_login:devise)
  def require_user_signed_in
    unless user_signed_in?

      # If the user came from a page, we can send them back.  Otherwise, send
      # them to the root path.
      if request.env['HTTP_REFERER']
        fallback_redirect = :back
      elsif defined?(root_path)
        fallback_redirect = root_path
      else
        fallback_redirect = "/"
      end

      redirect_to fallback_redirect, flash: {error: "You must be signed in to view this page."}
    end
  end

end

app/controllers/bills_controller.rb
class BillsController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_bill, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /bills
  # GET /bills.json
  def index
    @bills = Bill.all
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)
    @bill.user = current_user
    @bill.save
    cost = bill_params[:cost]
    pgi = bill_params[:payment_group_id]

    number = PaymentGroup.count('id', :id => pgi)

    div = cost.to_f / number.to_f

    people = User.where.not(id: current_user.id)

    people.each do |person|
      payment = Payment.new(user_id: person.id, bill_id: @bill.id, amount: div, paid: false, method: "PayPal")
      payment.save!
    end


    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:name, :description, :image, :cost, :payment_group_id, :user_id, :group_id, :paid)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  include ApplicationHelper

  def new
    super
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end

  def edit
    super
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include ApplicationHelper

  def create
    super
  end

  def new
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/bills/_form.html.erb
<%= form_for @bill, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :description, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :image, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :image, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "Payment Group", :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.collection_select(:payment_group_id, PaymentGroup.all, :id, :name, :include_blank => true) %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :cost, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :cost, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  bills_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/bills/edit.html.erb
<%- model_class = Bill -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Bill %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bills/index.html.erb
<%- model_class = Bill -%>
<div class="page-header">
  <h1><%=t '.title', :default => Bill %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:cost) %></th>
      <th><%= model_class.human_attribute_name(:paid) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.id %></td>
        <td><%= bill.name %></td>
        <td><%= bill.description %></td>
        <td><%= bill.image %></td>
        <td><%= bill.cost %></td>
        <td><%= bill.paid %></td>
        <td><%=l bill.created_at, format: :long %></td>
        <td>
          <%= link_to bill_path(bill), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to bill_path(bill), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bill_path,
            :class => 'btn btn-primary' %>

app/views/bills/new.html.erb
<%- model_class = Bill -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Bill %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bills/show.html.erb
<%- model_class = Bill -%>
<div class="page-header">
  <h1><%=t '.title', :default => Bill %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @bill.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:description) %></dt>
      <dd><pre class="prettyprint"><%= @bill.description %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:image) %></dt>
      <dd><pre class="prettyprint"><%= @bill.image %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:cost) %></dt>
      <dd><pre class="prettyprint"><%= @bill.cost %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:paid) %></dt>
      <dd><pre class="prettyprint"><%= @bill.paid %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              bills_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bill_path(@bill), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bill_path(@bill),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/elements/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to image_tag('logo-t.png', height: '75'), defined?(root_path) ? root_path : "#"%>

  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">


            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hello <%= current_user.name.strip.split(/\s+/)[0].to_s %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/elements/_pending_in.html.erb
  <div class="col-md-6">
  <h2>Incoming Payments</h2>

<% @payments = Payment.where(:user_id => current_user, :paid => false) %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>What</th>
      <th>Where</th>
      <th>When</th>
      <th>Amount</th>
    </tr>
  </thead>
  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.bill.name %></td>
        <td><%= payment.bill.payment_group.name %></td>
        <td><%= payment.created_at.strftime("%H:%M %d-%m-%Y") %></td>
        <td><%= payment.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/elements/_pending_out.html.erb
  <div class="col-md-6">
  <h2>Pending</h2>

<% @payments = Payment.where(:user_id => current_user, :paid => false) %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>What</th>
      <th>Where</th>
      <th>When</th>
      <th>Amount</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.bill.name %></td>
        <td><%= payment.bill.payment_group.name %></td>
        <td><%= payment.created_at.strftime("%H:%M %d-%m-%Y") %></td>
        <td><%= payment.amount %></td>
        <td>Yes/No</td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Divvly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
<meta name="viewport" content="width=device-width, initial-scale=1"/><!-- Prelang: Analytics / Google Analytics -->
    <%= analytics_init if Rails.env.production? or Rails.env.development? %></head>
<body>
<%= render partial: "elements/navbar" %>
<%= bootstrap_flash %>


<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<% if user_signed_in? %>
	<div class="row">
		<%= render partial: 'elements/pending_out' %>
		<%= render partial: 'elements/pending_in' %>
	</div>
<% else %>
<h1>Divvly</h1>
<p>Login to continue</p>
<% end %>

app/views/payments/_form.html.erb
<%= form_for @payment, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :method, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :method, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :paid, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.check_box :paid, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  payments_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/payments/edit.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Payment %></h1>
</div>
<%= render :partial => 'form' %>

app/views/payments/index.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => Payment %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:method) %></th>
      <th><%= model_class.human_attribute_name(:paid) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.id %></td>
        <td><%= payment.method %></td>
        <td><%= payment.paid %></td>
        <td><%=l payment.created_at, format: :long %></td>
        <td>
          <%= link_to payment_path(payment), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to payment_path(payment), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_payment_path,
            :class => 'btn btn-primary' %>

app/views/payments/new.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Payment %></h1>
</div>
<%= render :partial => 'form' %>

app/views/payments/show.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => Payment %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:method) %></dt>
      <dd><pre class="prettyprint"><%= @payment.method %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:paid) %></dt>
      <dd><pre class="prettyprint"><%= @payment.paid %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              payments_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_payment_path(@payment), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              payment_path(@payment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>